Optionally output cytoscape json files
leoisl/plasnet pull request #59
Opened 2024-06-28 12:22 UTC by babayagaofficial

Allows the user to optionally output the html visualisations, json files to be manually loaded into cytoscape, or both. The default is just the html visualisations. For the json files, also included in templates a style file in xml format to be used in cytoscape that is similar to the format used in the html visualisations (although stars are replaced with diamonds as cytoscape doesn't seem to allow for stars as node shape).

2024-07-03 03:21 UTC, leoisl requested changes
Hey @babayagaofficial , thanks for this PR, I really appreciate it! Just two minor questions!

2024-07-03 03:21 UTC, leoisl commented on plasnet/output_producer.py
> +        OutputProducer._write_html_for_all_subgraphs(communities, outdir, output_type)
Should this be called even if `output_type == json`?

2024-07-03 03:21 UTC, leoisl commented on plasnet/output_producer.py
> +        OutputProducer._write_html_for_all_subgraphs(subcommunities, outdir, output_type)
Should this be called even if `output_type == json`?

2024-07-03 08:16 UTC, babayagaofficial commented on plasnet/output_producer.py
> +        OutputProducer._write_html_for_all_subgraphs(communities, outdir, output_type)
I've actually hijacked this function to write both json and html as needed. Might be worth renaming the function to something like `write_vis_for_all_subgraphs` for clarity?

2024-08-19 04:57 UTC, leoisl commented
LGTM, thanks a lot @babayagaofficial !

2024-08-19 04:57 UTC, merged